export const FEEDS_TABS = [
  { id: 'flights',   label: 'Flights',   src: 'https://globe.adsbexchange.com/?lat=20&lon=0&zoom=3' },
  { id: 'weather',   label: 'Weather',   src: 'https://embed.windy.com/embed2.html?lat=20&lon=0&zoom=3&level=surface&overlay=wind&menu=&message=&marker=&calendar=&pressure=&type=map&location=coordinates&detail=&metricWind=kt&metricTemp=%C2%B0C&radarRange=-1' },
  { id: 'cyber',     label: 'Cyber',     src: 'https://threatmap.checkpoint.com/' },
  { id: 'wildfires', label: 'Wildfires', src: 'https://firms.modaps.eosdis.nasa.gov/map/' },
  { id: 'marine',    label: 'Marine',    src: 'https://www.myshiptracking.com/' },
]

export const CONFLICTS = [
  {
    name: 'Gaza', lat: 31.35, lng: 34.30, category: 'conflict', status: 'ongoing', typeStr: 'Conflict', country: 'Palestine',
    parties: ['Israel', 'Hamas'],
    description: 'Israeli military operations following Oct 7 2023 Hamas attack. Severe humanitarian crisis with mass civilian displacement.',
    startYear: 2023,
    source: 'https://acleddata.com',
  },
  {
    name: 'Kyiv Oblast', lat: 50.45, lng: 30.52, category: 'conflict', status: 'ongoing', typeStr: 'Conflict', country: 'Ukraine',
    parties: ['Ukraine', 'Russia'],
    description: 'Full-scale Russian invasion launched Feb 2022. Active frontlines across east and south Ukraine.',
    startYear: 2022,
    source: 'https://acleddata.com',
  },
  {
    name: 'Khartoum', lat: 15.55, lng: 32.53, category: 'conflict', status: 'ongoing', typeStr: 'Conflict', country: 'Sudan',
    parties: ['Sudanese Armed Forces', 'Rapid Support Forces'],
    description: "Civil war between SAF and RSF since Apr 2023. One of the world's largest displacement crises with 150,000+ killed.",
    startYear: 2023,
    source: 'https://acleddata.com',
  },
  {
    name: 'Donbas', lat: 48.01, lng: 37.80, category: 'conflict', status: 'ongoing', typeStr: 'Conflict', country: 'Ukraine',
    parties: ['Ukraine', 'Russia'],
    description: 'Russian-occupied territories and active frontline. Heavy shelling and attritional ground warfare ongoing.',
    startYear: 2014,
    source: 'https://acleddata.com',
  },
  {
    name: 'West Bank', lat: 31.95, lng: 35.30, category: 'conflict', status: 'alert', typeStr: 'Conflict', country: 'Palestine',
    parties: ['Israel', 'Palestinian groups'],
    description: 'Israeli raids, settler violence and Palestinian attacks ongoing since Oct 2023 escalation.',
    startYear: 2023,
    source: 'https://acleddata.com',
  },
  {
    name: 'Cabo Delgado', lat: -12.33, lng: 40.51, category: 'earthquake', status: 'ongoing', typeStr: 'Violence', country: 'Mozambique',
    parties: ['Mozambique Armed Forces', 'ISIS-linked insurgents'],
    description: 'Islamist insurgency in northern Mozambique displacing over 1 million civilians since 2017.',
    startYear: 2017,
    source: 'https://acleddata.com',
  },
  {
    name: 'Sahel/Mali', lat: 17.57, lng: -4.00, category: 'drought', status: 'ongoing', typeStr: 'Insecurity', country: 'Mali',
    parties: ['Malian junta / Wagner Group', 'Jihadist coalitions'],
    description: 'Jihadist insurgency across the Sahel corridor. Military juntas have replaced elected governments.',
    startYear: 2012,
    source: 'https://acleddata.com',
  },
  {
    name: 'Rakhine/Myanmar', lat: 20.14, lng: 92.90, category: 'conflict', status: 'ongoing', typeStr: 'Conflict', country: 'Myanmar',
    parties: ['Myanmar military (SAC)', 'Arakan Army and resistance forces'],
    description: 'Civil war following Feb 2021 coup. Multiple armed groups contest military junta across the country.',
    startYear: 2021,
    source: 'https://acleddata.com',
  },
  {
    name: 'South Kivu', lat: -2.99, lng: 28.85, category: 'earthquake', status: 'ongoing', typeStr: 'Violence', country: 'DRC',
    parties: ['DRC Armed Forces', 'M23 / Rwanda-backed rebels'],
    description: 'M23 offensive backed by Rwanda controls territory in eastern DRC. Ongoing displacement and atrocities.',
    startYear: 2022,
    source: 'https://acleddata.com',
  },
  {
    name: 'Idlib', lat: 35.93, lng: 36.63, category: 'earthquake', status: 'ongoing', typeStr: 'Conflict', country: 'Syria',
    parties: ['Hayat Tahrir al-Sham', 'Syrian Armed Forces'],
    description: 'Last major opposition stronghold. Fragile ceasefire with periodic airstrikes and clashes.',
    startYear: 2011,
    source: 'https://acleddata.com',
  },
  {
    name: 'Hajjah/Yemen', lat: 15.69, lng: 43.60, category: 'drought', status: 'ongoing', typeStr: 'Insecurity', country: 'Yemen',
    parties: ['Houthi movement (Ansar Allah)', 'Saudi-led coalition / Yemeni government forces'],
    description: "Saudi-led coalition intervention in Yemen's civil war. Catastrophic humanitarian crisis with famine conditions and mass civilian casualties.",
    startYear: 2015,
    source: 'https://acleddata.com',
  },
  {
    name: 'Tigray', lat: 14.03, lng: 38.31, category: 'drought', status: 'ongoing', typeStr: 'Insecurity', country: 'Ethiopia',
    parties: ['Ethiopian federal forces / Eritrea', 'Tigray People\'s Liberation Front (TPLF)'],
    description: 'Devastating conflict in northern Ethiopia resulting in hundreds of thousands of deaths and mass famine. Ceasefire signed Nov 2022.',
    startYear: 2020,
    source: 'https://acleddata.com',
  },
  {
    name: 'Borno/Nigeria', lat: 11.85, lng: 13.15, category: 'other', status: 'ongoing', typeStr: 'Insecurity', country: 'Nigeria',
    parties: ['Nigerian Armed Forces / CJTF', 'Boko Haram / ISWAP'],
    description: 'Long-running Islamist insurgency in northeast Nigeria and the Lake Chad Basin displacing millions and causing widespread atrocities.',
    startYear: 2009,
    source: 'https://acleddata.com',
  },
  {
    name: 'Oromia', lat: 8.00, lng: 38.00, category: 'other', status: 'ongoing', typeStr: 'Insecurity', country: 'Ethiopia',
    parties: ['Ethiopian federal forces', 'Oromo Liberation Army (OLA/Shane)'],
    description: 'Insurgency by Oromo armed group against federal government. Widespread civilian casualties and displacement in western and southern Oromia.',
    startYear: 2018,
    source: 'https://acleddata.com',
  },
  {
    name: 'Kunduz', lat: 36.72, lng: 68.87, category: 'other', status: 'past', typeStr: 'Conflict', country: 'Afghanistan',
    parties: ['Afghan government forces / NATO', 'Taliban'],
    description: 'Taliban seized Kunduz city in 2015 and 2016 before its permanent fall during the 2021 collapse of the Afghan government.',
    startYear: 2015,
    source: 'https://acleddata.com',
  },
  {
    name: 'Balochistan', lat: 28.49, lng: 65.09, category: 'other', status: 'ongoing', typeStr: 'Conflict', country: 'Pakistan',
    parties: ['Pakistani security forces', 'Baloch Liberation Army and affiliated groups'],
    description: "Separatist insurgency in Pakistan's largest province. Enforced disappearances, targeted killings and militant attacks ongoing.",
    startYear: 2004,
    source: 'https://acleddata.com',
  },
  {
    name: 'Manipur', lat: 24.66, lng: 93.90, category: 'other', status: 'ongoing', typeStr: 'Conflict', country: 'India',
    parties: ['Meitei community', 'Kuki-Zo community'],
    description: 'Ethnic violence between Meitei and Kuki-Zo communities erupted May 2023. Over 200 killed and 60,000 displaced.',
    startYear: 2023,
    source: 'https://acleddata.com',
  },
  {
    name: 'Abyei', lat: 9.60, lng: 28.43, category: 'other', status: 'ongoing', typeStr: 'Conflict', country: 'Sudan',
    parties: ['Sudan', 'South Sudan / Ngok Dinka community'],
    description: 'Disputed oil-rich territory claimed by both Sudan and South Sudan. Periodic intercommunal violence and unresolved political status.',
    startYear: 2011,
    source: 'https://acleddata.com',
  },
  {
    name: 'Nakhchivan', lat: 39.20, lng: 45.41, category: 'other', status: 'past', typeStr: 'Conflict', country: 'Azerbaijan',
    parties: ['Azerbaijan', 'Armenia'],
    description: 'Clashes around the Nakhchivan exclave during the 2020 Nagorno-Karabakh war. Azerbaijani 2023 offensive resolved the broader conflict.',
    startYear: 2020,
    source: 'https://acleddata.com',
  },
  {
    name: 'Marawi/Philippines', lat: 7.99, lng: 124.29, category: 'other', status: 'past', typeStr: 'Conflict', country: 'Philippines',
    parties: ['Armed Forces of the Philippines', 'Maute group / ISIS-affiliated fighters'],
    description: 'ISIS-affiliated militants seized Marawi City in May 2017. Five-month siege ended October 2017, devastating the city.',
    startYear: 2017,
    source: 'https://acleddata.com',
  },
]

export const WILDFIRES_STATIC = [
  {
    name: 'Canadian Boreal Zone', lat: 56.0, lng: -105.0, country: 'Canada',
    description: 'Recurrent boreal forest fires. Record 2023 season burned 18M hectares across British Columbia and Alberta.',
    season: 'Jun–Sep',
    source: 'https://firms.modaps.eosdis.nasa.gov',
  },
  {
    name: 'Amazon Basin', lat: -8.0, lng: -63.0, country: 'Brazil',
    description: 'Deforestation-driven fires peak in dry season. Accelerating loss of primary rainforest across Brazil and Bolivia.',
    season: 'Jul–Oct',
    source: 'https://firms.modaps.eosdis.nasa.gov',
  },
  {
    name: 'Siberia/Yakutia', lat: 62.0, lng: 130.0, country: 'Russia',
    description: 'Permafrost fires releasing stored carbon. 2021 set records with 18M hectares burned.',
    season: 'Jun–Aug',
    source: 'https://firms.modaps.eosdis.nasa.gov',
  },
  {
    name: 'SE Australia', lat: -33.0, lng: 149.0, country: 'Australia',
    description: 'Black Summer 2019–2020 burned 18.6M hectares. Eucalyptus forest remains highly fire-prone.',
    season: 'Nov–Mar',
    source: 'https://firms.modaps.eosdis.nasa.gov',
  },
  {
    name: 'Greece/Mediterranean', lat: 37.5, lng: 22.0, country: 'Greece',
    description: 'Recurring fires across Attica, Evros and Rhodes driven by Mediterranean drought and heat.',
    season: 'Jul–Sep',
    source: 'https://firms.modaps.eosdis.nasa.gov',
  },
  {
    name: 'California Corridor', lat: 37.0, lng: -119.0, country: 'USA',
    description: 'Year-round fire risk driven by drought and Santa Ana wind events. LA Basin fires Jan 2025 destroyed 12,000+ structures.',
    season: 'Aug–Nov',
    source: 'https://firms.modaps.eosdis.nasa.gov',
  },
  {
    name: 'Central Africa', lat: -5.0, lng: 25.0, country: 'DRC',
    description: 'Annual savanna burns for land clearing across Congo Basin. Satellite detects tens of thousands of fires yearly.',
    season: 'Jun–Sep',
    source: 'https://firms.modaps.eosdis.nasa.gov',
  },
  {
    name: 'SE Asia Peatlands', lat: 0.0, lng: 112.0, country: 'Indonesia',
    description: 'Peatland drainage fires in Borneo and Sumatra release massive carbon and produce toxic regional haze.',
    season: 'Jul–Oct',
    source: 'https://firms.modaps.eosdis.nasa.gov',
  },
]

export const PIRACY_ZONES = [
  { name: 'Gulf of Guinea',    bounds: [[ 0, -3], [ 5, 10]] },
  { name: 'Strait of Malacca', bounds: [[ 1,100], [ 6,105]] },
  { name: 'Gulf of Aden',      bounds: [[11, 42], [16, 52]] },
  { name: 'Red Sea',           bounds: [[12, 32], [28, 44]] },
]

export const CMAP_STYLE = {
  conflict:   { size: 14, color: '#e8294a', pulse: true  },
  flood:      { size: 10, color: '#4a9eff', pulse: false },
  earthquake: { size: 10, color: '#f07c2a', pulse: false },
  drought:    { size: 8,  color: '#f5c842', pulse: false },
  other:      { size: 8,  color: '#6e8098', pulse: false },
}
